### ISSUE TITLE
Canary itself is incompatible with 1.20.6

### ISSUE THREAD

**Issue by icehorse2401** [devOS-Sanity-Edition/canary#2]
Canary itself is incompatible with 1.20.6

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Canary' (canary) 2.0.13 with any version that is compatible with:
		 - minecraft 1.20.6
More details:
	 - Mod 'Canary' (canary) 2.0.13 requires version >=1.20.6 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

null[03:40:09] [main/INFO]:
 Loading Minecraft 1.20.6 with Fabric Loader 0.15.10
[03:40:09] [main/WARN]:
 Mod resolution failed
[03:40:09] [main/INFO]:
 Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED canary 2.0.13 {depends minecraft @ [>=>=1.20.6]}, ROOT_FORCELOAD_SINGLE canary 2.0.13]
[03:40:09] [main/INFO]:
 Reason: [HARD_DEP canary 2.0.13 {depends minecraft @ [>=>=1.20.6]}]
[03:40:09] [main/INFO]:
 Fix: add [], remove [], replace [[canary 2.0.13] -> add:canary 1 ([(-∞,∞)])]
[03:40:09] [main/ERROR]:
 Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Canary' (canary) 2.0.13 with any version that is compatible with:
		 - minecraft 1.20.6
More details:
	 - Mod 'Canary' (canary) 2.0.13 requires version >=1.20.6 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]

**Comment by TropheusJ** [comment]
Horrendous error message 
> `>=>=1.20.6`

Oops

**Comment by icehorse2401** [comment]
> Horrendous error message
> 
> > `>=>=1.20.6`
> 
> Oops

It’ll be updated right?

**Comment by TropheusJ** [comment]
Yes

**Comment by tractorbeam0** [comment]
It would seem that this issue is still present? Or at least, it's present when downloading with prism launcher (I downloaded 2.0 with Prism, from Modrinth)

**Comment by TropheusJ** [comment]
oops completely forgot

**Comment by TropheusJ** [comment]
fixed in 2.0.16
